apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: omniknow-backend-hpa
  namespace: omniknow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omniknow-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70